### ISSUE TITLE
Changing dark/ bright

### ISSUE THREAD

**Issue by theimo1221** [pmaji/eth_python_tracker#27]
Hello,

what do you guys think about changing current dark/ bright to an algorithm based color.

This way you could see a difference between 1, 4, 6 and 100 unique Orders.

Currently 1=4 and 6=100.

Additionally if we touch this, we should think about making it readable for people with red-green issue

Thanks and Greets

Theimo

Edit: Needed Tasks
- [x] create a button that changes the color coding to something that red/green color-blind people can use
- [x] implemented color based on unique orders in #37
- [ ] discuss continuous dark/ bright vs slider with border

**Comment by pmaji** [comment]
Hmm I know you closed this but it's an interesting idea @theimo1221, although I would take it a bit differently. Here's what I think.

I want to have a slider of sorts (I think this would be a Plotly callback) with which the user can control the parameter that changes the coloring. I.e. the default is 5, but they can change it to 10 which would then make it so that only price points with 10 or more unique orders are colored with the bright red / bright green.

**Comment by pmaji** [comment]
- [ ] create a button that changes the color coding to something that red/green color-blind people can use
- [ ] create a slider or other input method by which users can control what number of orders they want to color-sort by (this would need to be something that is distinct for EACH currency pair.

@theimo1221  adding these next steps for this issue.

**Comment by theimo1221** [comment]
It´s not closed, I just referenced this from a closed issue.

I partly disagree with the slider.  We have to consider how much influence the visitor has on the Dash App, cause he changes data/ settings for other users as well, if it´s hosted from us.

**Comment by theimo1221** [comment]
In #37 I added the color based on unique orders and inverted dark/ bright to highlight the "bad boys"
If you are comfortable with changes in #37 you can close this issue after merge.

**Comment by theimo1221** [comment]
Closed cause of #41 was approved
