### ISSUE TITLE
Add selection of Pairs

### ISSUE THREAD

**Issue by theimo1221** [pmaji/eth_python_tracker#28]
Hello team,

needed Tasks:

- [x]  Add Js function to hide/ shown specific graphs (solved in #40)
- [x] Decrease Callbacks/ Load to one (as well included in #40)
- [ ]  Choose Method of selection
Dropdown, Radio Buttons?
- [ ]  Decide if user can change Pairs on client Side
I recommend keeping tested Pairs in Python Code to ensure stability and user expierience

Thanks and Greets

Theimo

**Comment by pmaji** [comment]
Love the idea of letting the user pick pairs. 
I'm not familiar enough with what would be easiest for JS, but I think maybe a Checkbox would be best, that way users could the choice to still show more than one pairing per page (something that JDAX doesn't do). We could set it so that default is to show just ETH/USD first to save on load time. 

Let me know what you think and what might be easiest via JS?

**Comment by theimo1221** [comment]
Okay if we do so. We should consider to just use one update for all data as written in #29

**Comment by theimo1221** [comment]
One update for all data achieved in #40
