### ISSUE TITLE
Zoom is lost when graph refresh

### ISSUE THREAD

**Issue by arsenicks** [pmaji/eth_python_tracker#3]
it's all in the title, it would be nice to stop refreshing when zoomed in, or better refresh but keep the zoom as it is!

**Comment by pmaji** [comment]
Hmmm... that's a great point @arsenicks. I'll do some googling and check on workarounds. I think the problem is that the way app refreshes work in Dash apps is by refreshing the function that constructs the layout, so whenever that happens, the zoom is also reset.

**Comment by theimo1221** [comment]
#24 should fix this, by adding the freeze button

**Comment by pmaji** [comment]
This has now been fixed thanks to new improvements. Shout-out to @theimo1221  for the great freeze button. FYI @theimo1221  if you have a second, could you include a 1 or 2 line comment near the button that explains what the javascript is doing there? I'm not great at java and think most folks visiting this project will by primarily Python-literate, so that would help them a bunch.
